version: '3'

services:
  web:
    build: .
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "31020:3000"
    networks:
      - planning
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - mongodb
    env_file:
      - .env
  mongodb:
    image: docker.io/bitnami/mongodb:5.0
    restart: always
    volumes:
      - '/opt/planning_v2:/bitnami/mongodb'
    networks:
      - planning

networks:
  planning:
    driver: bridge
