version: '2'

services:
  web:
#    build: .
    image: ghcr.io/kernoeb/planningsup/planning
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "31020:3000"
    networks:
      - planning
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - MONGODB_URL=mongodb:27017
      - TZ=Europe/Paris
  mongodb:
    image: docker.io/bitnami/mongodb:5.0
    restart: always
    ports:
      - "27017"
    volumes:
      - '/opt/planning_v2:/bitnami/mongodb'
    networks:
      - planning

networks:
  planning:
    driver: bridge
